repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # check python requirements
  - repo: https://github.com/pdm-project/pdm
    rev: 2.11.2 # a PDM release exposing the hook
    hooks:
      - id: pdm-lock-check
